"""Add Fields reason and severity to transaction model

Revision ID: 5d7a9d3b50cd
Revises: d2b11309b4ee
Create Date: 2026-07-17 09:09:35.911455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d7a9d3b50cd'
down_revision: Union[str, Sequence[str], None] = 'd2b11309b4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
