"""remove severity field from Transactions model, add date reviewed field

Revision ID: 784483835407
Revises: 5d7a9d3b50cd
Create Date: 2026-07-21 08:52:04.262161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '784483835407'
down_revision: Union[str, Sequence[str], None] = '5d7a9d3b50cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
